# Workflow name
name: frontend pipeline


# Triggers for the workflow
on:
  push:
   branches:
      - main
  pull_request:
   branches:
      - main
   paths:
      - 'frontend/**'  # Trigger on pull requests that change files in the frontend folder
  workflow_dispatch:  # Allow manual triggering of the workflow



jobs:
  lint_job:
    runs-on: ubuntu-latest
    defaults:  
     run:
      shell: bash
      working-directory: ./frontend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
         node-version: latest

      - name: Install dependencies
        run:  npm ci

      - name: Run Lint 
        run: npm run lint

    

    
