# Workflow name
name: frontend pipeline


# Triggers for the workflow
on:
  push:
   branches:
      - main
  pull_request:
   branches:
      - main
   paths:
      - 'frontend/**'  # Trigger on pull requests that change files in the frontend folder
  workflow_dispatch:  # Allow manual triggering of the workflow



jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: |
          cd frontend  # Navigate to the frontend directory
          npm install  # Install dependencies

      - name: Run lint
        run: |
          cd frontend  # Navigate to the frontend directory
          npm run lint  # Run the linter
    

    
