# Workflow name
name: frontend pipeline


# Triggers for the workflow
on:
  push:
   branches:
      - main
  pull_request:
   branches:
      - main
   paths:
      - 'frontend/**'  # Trigger on pull requests that change files in the frontend folder
  workflow_dispatch:  # Allow manual triggering of the workflow

  # Scheduled trigger at 5:00 AM UTC, Monday through Friday
  schedule:
    - cron: '0 5 * * 1-5'

# Jobs defined in the workflow
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Node.js 
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: latest

      # - name: Print a message for main branch
      #   if: github.ref == 'refs/heads/main'
      #   run: echo "This is the main branch."

      # - name: Print a message for non-main branches
      #   if: github.ref != 'refs/heads/main'
      #   run: echo "This is not the main branch."

      - name: Run lint
        run: |
              cd frontend
              npm run lint

      # - name: Debug message
      #   if: env.DEBUG == 'true'
      #   run: echo "Debugging is enabled."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Node.js 
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: latest

      # - name: Print a message for main branch
      #   if: github.ref == 'refs/heads/main'
      #   run: echo "This is the main branch."

      # - name: Print a message for non-main branches
      #   if: github.ref != 'refs/heads/main'
      #   run: echo "This is not the main branch."

      - name: Run tests
        run: |
              cd frontend
              # Install dependencies
              npm ci

              # Run the tests interactively. You'll need to press `a` to run the tests
              npm test

              # OR simulate running the tests in a CI environment
              CI=true npm test

    

  # post-build-actions:
  #   needs: [lint, test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Publish test results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: test-results
  #         path: test-results.xml
